/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AppointmentStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Appointment = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : AppointmentStatus,
  'customerPhone' : IDL.Text,
  'date' : IDL.Int,
  'stylistId' : IDL.Nat,
  'notes' : IDL.Opt(IDL.Text),
  'serviceId' : IDL.Nat,
  'customerEmail' : IDL.Text,
  'timeSlot' : IDL.Text,
});
export const GalleryItem = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
});
export const Service = IDL.Record({
  'id' : IDL.Nat,
  'duration' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Nat,
});
export const Stylist = IDL.Record({
  'id' : IDL.Nat,
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'specialties' : IDL.Vec(IDL.Text),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bookAppointment' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Int,
        IDL.Text,
        IDL.Opt(IDL.Text),
      ],
      [Appointment],
      [],
    ),
  'getAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'getAllGalleryItems' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
  'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getAllStylists' : IDL.Func([], [IDL.Vec(Stylist)], ['query']),
  'getAppointmentById' : IDL.Func([IDL.Nat], [Appointment], ['query']),
  'getAppointmentsByDateRange' : IDL.Func(
      [IDL.Int, IDL.Int],
      [IDL.Vec(Appointment)],
      ['query'],
    ),
  'getAvailableTimeSlots' : IDL.Func(
      [IDL.Nat, IDL.Int],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGalleryItemById' : IDL.Func([IDL.Nat], [GalleryItem], ['query']),
  'getServiceById' : IDL.Func([IDL.Nat], [Service], ['query']),
  'getStylistById' : IDL.Func([IDL.Nat], [Stylist], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initialize' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateAppointmentStatus' : IDL.Func(
      [IDL.Nat, AppointmentStatus],
      [Appointment],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AppointmentStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Appointment = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : AppointmentStatus,
    'customerPhone' : IDL.Text,
    'date' : IDL.Int,
    'stylistId' : IDL.Nat,
    'notes' : IDL.Opt(IDL.Text),
    'serviceId' : IDL.Nat,
    'customerEmail' : IDL.Text,
    'timeSlot' : IDL.Text,
  });
  const GalleryItem = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
  });
  const Service = IDL.Record({
    'id' : IDL.Nat,
    'duration' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Nat,
  });
  const Stylist = IDL.Record({
    'id' : IDL.Nat,
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'specialties' : IDL.Vec(IDL.Text),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bookAppointment' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Int,
          IDL.Text,
          IDL.Opt(IDL.Text),
        ],
        [Appointment],
        [],
      ),
    'getAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'getAllGalleryItems' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
    'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getAllStylists' : IDL.Func([], [IDL.Vec(Stylist)], ['query']),
    'getAppointmentById' : IDL.Func([IDL.Nat], [Appointment], ['query']),
    'getAppointmentsByDateRange' : IDL.Func(
        [IDL.Int, IDL.Int],
        [IDL.Vec(Appointment)],
        ['query'],
      ),
    'getAvailableTimeSlots' : IDL.Func(
        [IDL.Nat, IDL.Int],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGalleryItemById' : IDL.Func([IDL.Nat], [GalleryItem], ['query']),
    'getServiceById' : IDL.Func([IDL.Nat], [Service], ['query']),
    'getStylistById' : IDL.Func([IDL.Nat], [Stylist], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initialize' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateAppointmentStatus' : IDL.Func(
        [IDL.Nat, AppointmentStatus],
        [Appointment],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };