/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Appointment {
  'id' : bigint,
  'customerName' : string,
  'status' : AppointmentStatus,
  'customerPhone' : string,
  'date' : bigint,
  'stylistId' : bigint,
  'notes' : [] | [string],
  'serviceId' : bigint,
  'customerEmail' : string,
  'timeSlot' : string,
}
export type AppointmentStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'confirmed' : null };
export interface GalleryItem {
  'id' : bigint,
  'title' : string,
  'description' : string,
  'imageUrl' : string,
}
export interface Service {
  'id' : bigint,
  'duration' : bigint,
  'name' : string,
  'description' : string,
  'category' : string,
  'price' : bigint,
}
export interface Stylist {
  'id' : bigint,
  'bio' : string,
  'name' : string,
  'specialties' : Array<string>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bookAppointment' : ActorMethod<
    [string, string, string, bigint, bigint, bigint, string, [] | [string]],
    Appointment
  >,
  'getAllAppointments' : ActorMethod<[], Array<Appointment>>,
  'getAllGalleryItems' : ActorMethod<[], Array<GalleryItem>>,
  'getAllServices' : ActorMethod<[], Array<Service>>,
  'getAllStylists' : ActorMethod<[], Array<Stylist>>,
  'getAppointmentById' : ActorMethod<[bigint], Appointment>,
  'getAppointmentsByDateRange' : ActorMethod<
    [bigint, bigint],
    Array<Appointment>
  >,
  'getAvailableTimeSlots' : ActorMethod<[bigint, bigint], Array<string>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGalleryItemById' : ActorMethod<[bigint], GalleryItem>,
  'getServiceById' : ActorMethod<[bigint], Service>,
  'getStylistById' : ActorMethod<[bigint], Stylist>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initialize' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateAppointmentStatus' : ActorMethod<
    [bigint, AppointmentStatus],
    Appointment
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];